"""Mock data for Product Catalog Service."""

CATEGORIES = [
    {
        "id": "CAT-01",
        "name": "Industrial Components",
        "parent_id": None,
        "children": [
            {
                "id": "CAT-01-01",
                "name": "Widgets & Fasteners",
                "parent_id": "CAT-01",
                "children": [],
            },
            {
                "id": "CAT-01-02",
                "name": "Valves & Fittings",
                "parent_id": "CAT-01",
                "children": [],
            },
            {
                "id": "CAT-01-03",
                "name": "Pipes & Tubing",
                "parent_id": "CAT-01",
                "children": [],
            },
        ],
    },
    {
        "id": "CAT-02",
        "name": "Electronics & Sensors",
        "parent_id": None,
        "children": [
            {
                "id": "CAT-02-01",
                "name": "Temperature Sensors",
                "parent_id": "CAT-02",
                "children": [],
            },
            {
                "id": "CAT-02-02",
                "name": "Cables & Connectors",
                "parent_id": "CAT-02",
                "children": [],
            },
            {
                "id": "CAT-02-03",
                "name": "Enclosures",
                "parent_id": "CAT-02",
                "children": [],
            },
        ],
    },
    {
        "id": "CAT-03",
        "name": "Motors & Drives",
        "parent_id": None,
        "children": [
            {
                "id": "CAT-03-01",
                "name": "AC Motors",
                "parent_id": "CAT-03",
                "children": [],
            },
            {
                "id": "CAT-03-02",
                "name": "DC Motors",
                "parent_id": "CAT-03",
                "children": [],
            },
            {
                "id": "CAT-03-03",
                "name": "Variable Frequency Drives",
                "parent_id": "CAT-03",
                "children": [],
            },
        ],
    },
]

PRODUCTS = [
    {
        "id": "PROD-001",
        "sku": "WIDGET-A100",
        "name": "Industrial Widget Type A",
        "description": "Heavy-duty industrial widget for assembly line use. Precision machined from carbon steel.",
        "category_id": "CAT-01-01",
        "category_name": "Widgets & Fasteners",
        "unit": "EA",
        "weight_kg": 0.25,
        "dimensions": {"length_cm": 5.0, "width_cm": 3.0, "height_cm": 2.0},
        "base_price": 12.50,
        "cost": 8.50,
        "currency": "USD",
        "status": "active",
        "min_order_quantity": 100,
        "lead_time_days": 7,
        "created_at": "2023-01-10T10:00:00Z",
        "updated_at": "2024-06-15T14:00:00Z",
    },
    {
        "id": "PROD-002",
        "sku": "BOLT-SS-M10",
        "name": "Stainless Steel Bolt M10x50",
        "description": "Grade A4-80 stainless steel hex bolt, M10 thread, 50mm length. DIN 933 standard.",
        "category_id": "CAT-01-01",
        "category_name": "Widgets & Fasteners",
        "unit": "EA",
        "weight_kg": 0.035,
        "dimensions": {"length_cm": 5.0, "width_cm": 1.7, "height_cm": 1.7},
        "base_price": 0.85,
        "cost": 0.45,
        "currency": "USD",
        "status": "active",
        "min_order_quantity": 500,
        "lead_time_days": 5,
        "created_at": "2023-01-12T10:00:00Z",
        "updated_at": "2024-03-20T11:00:00Z",
    },
    {
        "id": "PROD-003",
        "sku": "SENSOR-TEMP-200",
        "name": "Temperature Sensor 200C Range",
        "description": "PT100 RTD temperature sensor with 200 degree Celsius range. 4-wire configuration, IP67 rated.",
        "category_id": "CAT-02-01",
        "category_name": "Temperature Sensors",
        "unit": "EA",
        "weight_kg": 0.15,
        "dimensions": {"length_cm": 10.0, "width_cm": 2.0, "height_cm": 2.0},
        "base_price": 45.00,
        "cost": 28.00,
        "currency": "USD",
        "status": "active",
        "min_order_quantity": 10,
        "lead_time_days": 14,
        "created_at": "2023-02-05T09:00:00Z",
        "updated_at": "2024-08-10T16:00:00Z",
    },
    {
        "id": "PROD-004",
        "sku": "CABLE-CAT6-100M",
        "name": "CAT6 Ethernet Cable 100m",
        "description": "Cat6 UTP ethernet cable, 100 meter spool. 23AWG solid copper, LSZH jacket. Fluke tested.",
        "category_id": "CAT-02-02",
        "category_name": "Cables & Connectors",
        "unit": "EA",
        "weight_kg": 4.5,
        "dimensions": {"length_cm": 30.0, "width_cm": 30.0, "height_cm": 15.0},
        "base_price": 89.99,
        "cost": 55.00,
        "currency": "USD",
        "status": "active",
        "min_order_quantity": 5,
        "lead_time_days": 10,
        "created_at": "2023-03-15T12:00:00Z",
        "updated_at": "2024-07-22T09:00:00Z",
    },
    {
        "id": "PROD-005",
        "sku": "ENCL-IP65-LG",
        "name": "IP65 Enclosure Large",
        "description": "Polycarbonate IP65-rated enclosure, large size. UV resistant, clear lid option. Wall mountable.",
        "category_id": "CAT-02-03",
        "category_name": "Enclosures",
        "unit": "EA",
        "weight_kg": 2.8,
        "dimensions": {"length_cm": 40.0, "width_cm": 30.0, "height_cm": 20.0},
        "base_price": 120.00,
        "cost": 75.00,
        "currency": "USD",
        "status": "active",
        "min_order_quantity": 1,
        "lead_time_days": 7,
        "created_at": "2023-04-20T14:00:00Z",
        "updated_at": "2024-05-18T10:00:00Z",
    },
    {
        "id": "PROD-006",
        "sku": "MOTOR-AC-5HP",
        "name": "AC Motor 5HP 3-Phase",
        "description": "TEFC 3-phase AC induction motor, 5 HP / 3.7 kW, 1750 RPM, 208-230/460V. NEMA 56C frame.",
        "category_id": "CAT-03-01",
        "category_name": "AC Motors",
        "unit": "EA",
        "weight_kg": 25.0,
        "dimensions": {"length_cm": 35.0, "width_cm": 20.0, "height_cm": 22.0},
        "base_price": 850.00,
        "cost": 520.00,
        "currency": "USD",
        "status": "active",
        "min_order_quantity": 1,
        "lead_time_days": 21,
        "created_at": "2023-05-10T08:00:00Z",
        "updated_at": "2024-09-05T13:00:00Z",
    },
    {
        "id": "PROD-007",
        "sku": "VALVE-GATE-2IN",
        "name": "Gate Valve 2 inch Brass",
        "description": "Brass gate valve, 2 inch NPT, 200 PSI WOG. Full port, rising stem design.",
        "category_id": "CAT-01-02",
        "category_name": "Valves & Fittings",
        "unit": "EA",
        "weight_kg": 1.5,
        "dimensions": {"length_cm": 15.0, "width_cm": 10.0, "height_cm": 8.0},
        "base_price": 35.00,
        "cost": 18.00,
        "currency": "USD",
        "status": "active",
        "min_order_quantity": 10,
        "lead_time_days": 5,
        "created_at": "2023-06-01T11:00:00Z",
        "updated_at": "2024-04-12T15:00:00Z",
    },
    {
        "id": "PROD-008",
        "sku": "PIPE-PVC-4IN",
        "name": "PVC Pipe 4 inch x 10ft",
        "description": "Schedule 40 PVC pipe, 4 inch diameter, 10 foot length. ASTM D1785 compliant.",
        "category_id": "CAT-01-03",
        "category_name": "Pipes & Tubing",
        "unit": "EA",
        "weight_kg": 5.2,
        "dimensions": {"length_cm": 305.0, "width_cm": 11.5, "height_cm": 11.5},
        "base_price": 22.50,
        "cost": 12.00,
        "currency": "USD",
        "status": "active",
        "min_order_quantity": 10,
        "lead_time_days": 3,
        "created_at": "2023-06-15T09:00:00Z",
        "updated_at": "2024-02-28T12:00:00Z",
    },
]

# Bill of Materials for MOTOR-AC-5HP (PROD-006)
BOMS = {
    "PROD-006": {
        "product_id": "PROD-006",
        "product_sku": "MOTOR-AC-5HP",
        "product_name": "AC Motor 5HP 3-Phase",
        "revision": "B",
        "effective_date": "2024-01-01",
        "components": [
            {"sku": "BOM-STATOR-5HP", "name": "Stator Assembly 5HP", "quantity": 1, "unit": "EA", "unit_cost": 180.00},
            {"sku": "BOM-ROTOR-5HP", "name": "Rotor Assembly 5HP", "quantity": 1, "unit": "EA", "unit_cost": 120.00},
            {"sku": "BOM-BEARING-6205", "name": "Ball Bearing 6205-2RS", "quantity": 2, "unit": "EA", "unit_cost": 8.50},
            {"sku": "BOM-HOUSING-56C", "name": "Motor Housing NEMA 56C", "quantity": 1, "unit": "EA", "unit_cost": 95.00},
            {"sku": "BOM-FAN-COOL", "name": "Cooling Fan Assembly", "quantity": 1, "unit": "EA", "unit_cost": 15.00},
            {"sku": "BOM-TERMBOX", "name": "Terminal Box with Leads", "quantity": 1, "unit": "EA", "unit_cost": 22.00},
            {"sku": "BOLT-SS-M10", "name": "Stainless Steel Bolt M10x50", "quantity": 8, "unit": "EA", "unit_cost": 0.45},
        ],
        "total_component_cost": 444.10,
        "labor_cost": 55.00,
        "overhead_cost": 20.90,
        "total_cost": 520.00,
    },
    "PROD-005": {
        "product_id": "PROD-005",
        "product_sku": "ENCL-IP65-LG",
        "product_name": "IP65 Enclosure Large",
        "revision": "A",
        "effective_date": "2023-06-01",
        "components": [
            {"sku": "BOM-ENCL-BASE", "name": "Enclosure Base Polycarbonate", "quantity": 1, "unit": "EA", "unit_cost": 28.00},
            {"sku": "BOM-ENCL-LID", "name": "Enclosure Clear Lid", "quantity": 1, "unit": "EA", "unit_cost": 18.00},
            {"sku": "BOM-GASKET-LG", "name": "IP65 Gasket Seal Large", "quantity": 1, "unit": "EA", "unit_cost": 5.50},
            {"sku": "BOM-HINGE-SS", "name": "Stainless Steel Hinge", "quantity": 2, "unit": "EA", "unit_cost": 3.00},
            {"sku": "BOM-LATCH-IP65", "name": "IP65 Latch", "quantity": 2, "unit": "EA", "unit_cost": 4.50},
            {"sku": "BOM-MOUNT-KIT", "name": "Wall Mount Kit", "quantity": 1, "unit": "EA", "unit_cost": 6.00},
        ],
        "total_component_cost": 68.00,
        "labor_cost": 5.00,
        "overhead_cost": 2.00,
        "total_cost": 75.00,
    },
}

PRICING = {
    "PROD-001": {
        "product_id": "PROD-001",
        "sku": "WIDGET-A100",
        "base_price": 12.50,
        "currency": "USD",
        "tiers": [
            {"min_quantity": 1, "max_quantity": 99, "unit_price": 12.50, "discount_pct": 0},
            {"min_quantity": 100, "max_quantity": 499, "unit_price": 11.25, "discount_pct": 10},
            {"min_quantity": 500, "max_quantity": 1999, "unit_price": 10.00, "discount_pct": 20},
            {"min_quantity": 2000, "max_quantity": None, "unit_price": 8.75, "discount_pct": 30},
        ],
    },
    "PROD-002": {
        "product_id": "PROD-002",
        "sku": "BOLT-SS-M10",
        "base_price": 0.85,
        "currency": "USD",
        "tiers": [
            {"min_quantity": 1, "max_quantity": 499, "unit_price": 0.85, "discount_pct": 0},
            {"min_quantity": 500, "max_quantity": 4999, "unit_price": 0.72, "discount_pct": 15},
            {"min_quantity": 5000, "max_quantity": None, "unit_price": 0.60, "discount_pct": 30},
        ],
    },
    "PROD-003": {
        "product_id": "PROD-003",
        "sku": "SENSOR-TEMP-200",
        "base_price": 45.00,
        "currency": "USD",
        "tiers": [
            {"min_quantity": 1, "max_quantity": 9, "unit_price": 45.00, "discount_pct": 0},
            {"min_quantity": 10, "max_quantity": 49, "unit_price": 40.50, "discount_pct": 10},
            {"min_quantity": 50, "max_quantity": None, "unit_price": 36.00, "discount_pct": 20},
        ],
    },
    "PROD-006": {
        "product_id": "PROD-006",
        "sku": "MOTOR-AC-5HP",
        "base_price": 850.00,
        "currency": "USD",
        "tiers": [
            {"min_quantity": 1, "max_quantity": 4, "unit_price": 850.00, "discount_pct": 0},
            {"min_quantity": 5, "max_quantity": 19, "unit_price": 807.50, "discount_pct": 5},
            {"min_quantity": 20, "max_quantity": None, "unit_price": 765.00, "discount_pct": 10},
        ],
    },
}

# Default pricing for products without explicit tiers
DEFAULT_PRICING_TEMPLATE = {
    "tiers": [
        {"min_quantity": 1, "max_quantity": None, "unit_price": None, "discount_pct": 0},
    ]
}
