"""Mock data for Sales Order Service."""

from datetime import date, datetime

CUSTOMERS = [
    {
        "id": "CUST-001",
        "name": "Acme Corporation",
        "email": "purchasing@acme.com",
        "phone": "+1-555-0101",
        "contact_person": "John Smith",
        "address": {
            "street": "123 Industrial Blvd",
            "city": "Chicago",
            "state": "IL",
            "postal_code": "60601",
            "country": "US",
        },
        "credit_limit": 500000.00,
        "payment_terms": "Net 30",
        "status": "active",
        "created_at": "2023-01-15T10:00:00Z",
    },
    {
        "id": "CUST-002",
        "name": "Global Tech Solutions",
        "email": "orders@globaltech.com",
        "phone": "+1-555-0102",
        "contact_person": "Sarah Johnson",
        "address": {
            "street": "456 Tech Park Drive",
            "city": "San Jose",
            "state": "CA",
            "postal_code": "95110",
            "country": "US",
        },
        "credit_limit": 750000.00,
        "payment_terms": "Net 45",
        "status": "active",
        "created_at": "2023-02-20T14:30:00Z",
    },
    {
        "id": "CUST-003",
        "name": "Midwest Manufacturing Inc.",
        "email": "procurement@midwestmfg.com",
        "phone": "+1-555-0103",
        "contact_person": "Robert Chen",
        "address": {
            "street": "789 Factory Road",
            "city": "Detroit",
            "state": "MI",
            "postal_code": "48201",
            "country": "US",
        },
        "credit_limit": 300000.00,
        "payment_terms": "Net 30",
        "status": "active",
        "created_at": "2023-03-10T09:15:00Z",
    },
    {
        "id": "CUST-004",
        "name": "Pacific Rim Distributors",
        "email": "orders@pacificrim.com",
        "phone": "+1-555-0104",
        "contact_person": "Linda Park",
        "address": {
            "street": "321 Harbor Way",
            "city": "Seattle",
            "state": "WA",
            "postal_code": "98101",
            "country": "US",
        },
        "credit_limit": 1000000.00,
        "payment_terms": "Net 60",
        "status": "active",
        "created_at": "2023-04-05T11:45:00Z",
    },
    {
        "id": "CUST-005",
        "name": "Southern Supply Co.",
        "email": "buy@southernsupply.com",
        "phone": "+1-555-0105",
        "contact_person": "James Williams",
        "address": {
            "street": "654 Commerce St",
            "city": "Atlanta",
            "state": "GA",
            "postal_code": "30301",
            "country": "US",
        },
        "credit_limit": 200000.00,
        "payment_terms": "Net 15",
        "status": "inactive",
        "created_at": "2023-05-18T16:00:00Z",
    },
]

ORDERS = [
    {
        "id": "SO-2024-00123",
        "customer_id": "CUST-001",
        "customer_name": "Acme Corporation",
        "status": "confirmed",
        "order_date": "2024-11-15",
        "required_date": "2024-12-01",
        "shipping_address": {
            "street": "123 Industrial Blvd",
            "city": "Chicago",
            "state": "IL",
            "postal_code": "60601",
            "country": "US",
        },
        "line_items": [
            {
                "line_number": 1,
                "sku": "WIDGET-A100",
                "product_name": "Industrial Widget Type A",
                "quantity": 500,
                "unit_price": 12.50,
                "total": 6250.00,
                "unit": "EA",
            },
            {
                "line_number": 2,
                "sku": "BOLT-SS-M10",
                "product_name": "Stainless Steel Bolt M10x50",
                "quantity": 2000,
                "unit_price": 0.85,
                "total": 1700.00,
                "unit": "EA",
            },
        ],
        "subtotal": 7950.00,
        "tax": 636.00,
        "shipping_cost": 150.00,
        "total": 8736.00,
        "currency": "USD",
        "payment_terms": "Net 30",
        "notes": "Deliver to loading dock B",
        "created_at": "2024-11-15T09:30:00Z",
        "updated_at": "2024-11-15T14:00:00Z",
    },
    {
        "id": "SO-2024-00124",
        "customer_id": "CUST-002",
        "customer_name": "Global Tech Solutions",
        "status": "processing",
        "order_date": "2024-11-16",
        "required_date": "2024-12-10",
        "shipping_address": {
            "street": "456 Tech Park Drive",
            "city": "San Jose",
            "state": "CA",
            "postal_code": "95110",
            "country": "US",
        },
        "line_items": [
            {
                "line_number": 1,
                "sku": "SENSOR-TEMP-200",
                "product_name": "Temperature Sensor 200C Range",
                "quantity": 100,
                "unit_price": 45.00,
                "total": 4500.00,
                "unit": "EA",
            },
            {
                "line_number": 2,
                "sku": "CABLE-CAT6-100M",
                "product_name": "CAT6 Ethernet Cable 100m",
                "quantity": 50,
                "unit_price": 89.99,
                "total": 4499.50,
                "unit": "EA",
            },
            {
                "line_number": 3,
                "sku": "ENCL-IP65-LG",
                "product_name": "IP65 Enclosure Large",
                "quantity": 25,
                "unit_price": 120.00,
                "total": 3000.00,
                "unit": "EA",
            },
        ],
        "subtotal": 11999.50,
        "tax": 959.96,
        "shipping_cost": 250.00,
        "total": 13209.46,
        "currency": "USD",
        "payment_terms": "Net 45",
        "notes": "",
        "created_at": "2024-11-16T11:00:00Z",
        "updated_at": "2024-11-17T08:30:00Z",
    },
    {
        "id": "SO-2024-00125",
        "customer_id": "CUST-003",
        "customer_name": "Midwest Manufacturing Inc.",
        "status": "shipped",
        "order_date": "2024-11-10",
        "required_date": "2024-11-25",
        "shipping_address": {
            "street": "789 Factory Road",
            "city": "Detroit",
            "state": "MI",
            "postal_code": "48201",
            "country": "US",
        },
        "line_items": [
            {
                "line_number": 1,
                "sku": "MOTOR-AC-5HP",
                "product_name": "AC Motor 5HP 3-Phase",
                "quantity": 10,
                "unit_price": 850.00,
                "total": 8500.00,
                "unit": "EA",
            },
        ],
        "subtotal": 8500.00,
        "tax": 510.00,
        "shipping_cost": 500.00,
        "total": 9510.00,
        "currency": "USD",
        "payment_terms": "Net 30",
        "notes": "Fragile - handle with care",
        "created_at": "2024-11-10T13:15:00Z",
        "updated_at": "2024-11-20T10:00:00Z",
    },
    {
        "id": "SO-2024-00126",
        "customer_id": "CUST-004",
        "customer_name": "Pacific Rim Distributors",
        "status": "draft",
        "order_date": "2024-11-18",
        "required_date": "2025-01-15",
        "shipping_address": {
            "street": "321 Harbor Way",
            "city": "Seattle",
            "state": "WA",
            "postal_code": "98101",
            "country": "US",
        },
        "line_items": [
            {
                "line_number": 1,
                "sku": "VALVE-GATE-2IN",
                "product_name": "Gate Valve 2 inch Brass",
                "quantity": 200,
                "unit_price": 35.00,
                "total": 7000.00,
                "unit": "EA",
            },
            {
                "line_number": 2,
                "sku": "PIPE-PVC-4IN",
                "product_name": "PVC Pipe 4 inch x 10ft",
                "quantity": 100,
                "unit_price": 22.50,
                "total": 2250.00,
                "unit": "EA",
            },
        ],
        "subtotal": 9250.00,
        "tax": 740.00,
        "shipping_cost": 350.00,
        "total": 10340.00,
        "currency": "USD",
        "payment_terms": "Net 60",
        "notes": "Awaiting customer confirmation",
        "created_at": "2024-11-18T15:45:00Z",
        "updated_at": "2024-11-18T15:45:00Z",
    },
    {
        "id": "SO-2024-00127",
        "customer_id": "CUST-001",
        "customer_name": "Acme Corporation",
        "status": "delivered",
        "order_date": "2024-10-20",
        "required_date": "2024-11-05",
        "shipping_address": {
            "street": "123 Industrial Blvd",
            "city": "Chicago",
            "state": "IL",
            "postal_code": "60601",
            "country": "US",
        },
        "line_items": [
            {
                "line_number": 1,
                "sku": "WIDGET-A100",
                "product_name": "Industrial Widget Type A",
                "quantity": 1000,
                "unit_price": 12.50,
                "total": 12500.00,
                "unit": "EA",
            },
        ],
        "subtotal": 12500.00,
        "tax": 1000.00,
        "shipping_cost": 200.00,
        "total": 13700.00,
        "currency": "USD",
        "payment_terms": "Net 30",
        "notes": "",
        "created_at": "2024-10-20T08:00:00Z",
        "updated_at": "2024-11-03T16:30:00Z",
    },
]

INVOICES = [
    {
        "id": "INV-2024-00501",
        "order_id": "SO-2024-00127",
        "customer_id": "CUST-001",
        "customer_name": "Acme Corporation",
        "status": "paid",
        "invoice_date": "2024-11-03",
        "due_date": "2024-12-03",
        "line_items": [
            {
                "description": "Industrial Widget Type A (SO-2024-00127)",
                "quantity": 1000,
                "unit_price": 12.50,
                "total": 12500.00,
            },
        ],
        "subtotal": 12500.00,
        "tax": 1000.00,
        "total": 13500.00,
        "amount_paid": 13500.00,
        "balance_due": 0.00,
        "currency": "USD",
        "payment_terms": "Net 30",
        "created_at": "2024-11-03T17:00:00Z",
    },
    {
        "id": "INV-2024-00502",
        "order_id": "SO-2024-00125",
        "customer_id": "CUST-003",
        "customer_name": "Midwest Manufacturing Inc.",
        "status": "sent",
        "invoice_date": "2024-11-20",
        "due_date": "2024-12-20",
        "line_items": [
            {
                "description": "AC Motor 5HP 3-Phase (SO-2024-00125)",
                "quantity": 10,
                "unit_price": 850.00,
                "total": 8500.00,
            },
        ],
        "subtotal": 8500.00,
        "tax": 510.00,
        "total": 9010.00,
        "amount_paid": 0.00,
        "balance_due": 9010.00,
        "currency": "USD",
        "payment_terms": "Net 30",
        "created_at": "2024-11-20T10:30:00Z",
    },
    {
        "id": "INV-2024-00503",
        "order_id": "SO-2024-00123",
        "customer_id": "CUST-001",
        "customer_name": "Acme Corporation",
        "status": "draft",
        "invoice_date": "2024-11-18",
        "due_date": "2024-12-18",
        "line_items": [
            {
                "description": "Industrial Widget Type A (SO-2024-00123)",
                "quantity": 500,
                "unit_price": 12.50,
                "total": 6250.00,
            },
            {
                "description": "Stainless Steel Bolt M10x50 (SO-2024-00123)",
                "quantity": 2000,
                "unit_price": 0.85,
                "total": 1700.00,
            },
        ],
        "subtotal": 7950.00,
        "tax": 636.00,
        "total": 8586.00,
        "amount_paid": 0.00,
        "balance_due": 8586.00,
        "currency": "USD",
        "payment_terms": "Net 30",
        "created_at": "2024-11-18T16:00:00Z",
    },
]
