"""Mock data for Procurement Service."""

SUPPLIERS = [
    {
        "id": "SUP-001",
        "name": "SteelWorks International",
        "email": "sales@steelworks-intl.com",
        "phone": "+1-555-0201",
        "contact_person": "Angela Torres",
        "address": {
            "street": "500 Foundry Lane",
            "city": "Pittsburgh",
            "state": "PA",
            "postal_code": "15201",
            "country": "US",
        },
        "payment_terms": "Net 30",
        "lead_time_days": 14,
        "rating": 4.5,
        "categories": ["raw_materials", "fasteners"],
        "status": "active",
        "created_at": "2022-06-15T10:00:00Z",
    },
    {
        "id": "SUP-002",
        "name": "ElectroParts Co.",
        "email": "orders@electroparts.com",
        "phone": "+1-555-0202",
        "contact_person": "Kevin Zhao",
        "address": {
            "street": "1200 Circuit Ave",
            "city": "Shenzhen",
            "state": "Guangdong",
            "postal_code": "518000",
            "country": "CN",
        },
        "payment_terms": "Net 45",
        "lead_time_days": 30,
        "rating": 4.2,
        "categories": ["electronics", "sensors", "cables"],
        "status": "active",
        "created_at": "2022-08-20T14:00:00Z",
    },
    {
        "id": "SUP-003",
        "name": "MotorDrive Systems",
        "email": "b2b@motordrive.com",
        "phone": "+1-555-0203",
        "contact_person": "Hans Gruber",
        "address": {
            "street": "75 Motorenweg",
            "city": "Stuttgart",
            "state": "Baden-Wurttemberg",
            "postal_code": "70173",
            "country": "DE",
        },
        "payment_terms": "Net 60",
        "lead_time_days": 21,
        "rating": 4.8,
        "categories": ["motors", "drives", "automation"],
        "status": "active",
        "created_at": "2023-01-10T09:00:00Z",
    },
    {
        "id": "SUP-004",
        "name": "PlumbPro Supply",
        "email": "wholesale@plumbpro.com",
        "phone": "+1-555-0204",
        "contact_person": "Maria Gonzalez",
        "address": {
            "street": "333 Pipeline Road",
            "city": "Houston",
            "state": "TX",
            "postal_code": "77001",
            "country": "US",
        },
        "payment_terms": "Net 30",
        "lead_time_days": 7,
        "rating": 4.0,
        "categories": ["valves", "pipes", "fittings"],
        "status": "active",
        "created_at": "2023-03-22T11:30:00Z",
    },
]

PURCHASE_ORDERS = [
    {
        "id": "PO-2024-00210",
        "supplier_id": "SUP-001",
        "supplier_name": "SteelWorks International",
        "status": "received",
        "order_date": "2024-10-15",
        "expected_date": "2024-10-29",
        "line_items": [
            {
                "line_number": 1,
                "sku": "WIDGET-A100",
                "product_name": "Industrial Widget Type A",
                "quantity_ordered": 5000,
                "quantity_received": 5000,
                "unit_price": 8.50,
                "total": 42500.00,
                "unit": "EA",
            },
        ],
        "subtotal": 42500.00,
        "tax": 0.00,
        "shipping_cost": 800.00,
        "total": 43300.00,
        "currency": "USD",
        "approved_by": "director_procurement",
        "approved_at": "2024-10-16T10:00:00Z",
        "notes": "Annual bulk order - batch 1",
        "created_at": "2024-10-15T09:00:00Z",
        "updated_at": "2024-10-30T14:00:00Z",
    },
    {
        "id": "PO-2024-00211",
        "supplier_id": "SUP-002",
        "supplier_name": "ElectroParts Co.",
        "status": "ordered",
        "order_date": "2024-11-05",
        "expected_date": "2024-12-05",
        "line_items": [
            {
                "line_number": 1,
                "sku": "SENSOR-TEMP-200",
                "product_name": "Temperature Sensor 200C Range",
                "quantity_ordered": 500,
                "quantity_received": 0,
                "unit_price": 28.00,
                "total": 14000.00,
                "unit": "EA",
            },
            {
                "line_number": 2,
                "sku": "CABLE-CAT6-100M",
                "product_name": "CAT6 Ethernet Cable 100m",
                "quantity_ordered": 200,
                "quantity_received": 0,
                "unit_price": 55.00,
                "total": 11000.00,
                "unit": "EA",
            },
        ],
        "subtotal": 25000.00,
        "tax": 0.00,
        "shipping_cost": 1500.00,
        "total": 26500.00,
        "currency": "USD",
        "approved_by": "director_procurement",
        "approved_at": "2024-11-06T08:30:00Z",
        "notes": "Sea freight - 30 day lead time",
        "created_at": "2024-11-05T14:00:00Z",
        "updated_at": "2024-11-06T08:30:00Z",
    },
    {
        "id": "PO-2024-00212",
        "supplier_id": "SUP-003",
        "supplier_name": "MotorDrive Systems",
        "status": "pending_approval",
        "order_date": "2024-11-18",
        "expected_date": "2024-12-09",
        "line_items": [
            {
                "line_number": 1,
                "sku": "MOTOR-AC-5HP",
                "product_name": "AC Motor 5HP 3-Phase",
                "quantity_ordered": 20,
                "quantity_received": 0,
                "unit_price": 520.00,
                "total": 10400.00,
                "unit": "EA",
            },
        ],
        "subtotal": 10400.00,
        "tax": 0.00,
        "shipping_cost": 600.00,
        "total": 11000.00,
        "currency": "USD",
        "approved_by": None,
        "approved_at": None,
        "notes": "Restock order triggered by low inventory alert",
        "created_at": "2024-11-18T11:00:00Z",
        "updated_at": "2024-11-18T11:00:00Z",
    },
    {
        "id": "PO-2024-00213",
        "supplier_id": "SUP-004",
        "supplier_name": "PlumbPro Supply",
        "status": "approved",
        "order_date": "2024-11-17",
        "expected_date": "2024-11-24",
        "line_items": [
            {
                "line_number": 1,
                "sku": "VALVE-GATE-2IN",
                "product_name": "Gate Valve 2 inch Brass",
                "quantity_ordered": 200,
                "quantity_received": 0,
                "unit_price": 18.00,
                "total": 3600.00,
                "unit": "EA",
            },
            {
                "line_number": 2,
                "sku": "PIPE-PVC-4IN",
                "product_name": "PVC Pipe 4 inch x 10ft",
                "quantity_ordered": 500,
                "quantity_received": 0,
                "unit_price": 12.00,
                "total": 6000.00,
                "unit": "EA",
            },
        ],
        "subtotal": 9600.00,
        "tax": 768.00,
        "shipping_cost": 400.00,
        "total": 10768.00,
        "currency": "USD",
        "approved_by": "director_procurement",
        "approved_at": "2024-11-17T16:00:00Z",
        "notes": "",
        "created_at": "2024-11-17T14:30:00Z",
        "updated_at": "2024-11-17T16:00:00Z",
    },
]

RECEIVING_RECORDS = [
    {
        "id": "RCV-2024-00601",
        "purchase_order_id": "PO-2024-00210",
        "supplier_id": "SUP-001",
        "warehouse_id": "WH-EAST-01",
        "received_date": "2024-10-30",
        "items": [
            {
                "sku": "WIDGET-A100",
                "quantity_expected": 5000,
                "quantity_received": 5000,
                "quantity_rejected": 0,
                "inspection_status": "passed",
            }
        ],
        "status": "completed",
        "received_by": "mike.thompson",
        "notes": "All items passed QC inspection",
        "created_at": "2024-10-30T09:00:00Z",
    },
]
