"""Mock data for Warehouse Management Service."""

WAREHOUSES = [
    {
        "id": "WH-EAST-01",
        "name": "East Coast Distribution Center",
        "location": {
            "street": "1000 Logistics Parkway",
            "city": "Newark",
            "state": "NJ",
            "postal_code": "07102",
            "country": "US",
        },
        "type": "distribution_center",
        "total_capacity_sqft": 150000,
        "used_capacity_sqft": 95000,
        "zones": [
            {"code": "WH-EAST-01-A", "name": "Zone A - Receiving", "type": "receiving", "temperature": "ambient"},
            {"code": "WH-EAST-01-B", "name": "Zone B - Bulk Storage", "type": "bulk_storage", "temperature": "ambient"},
            {"code": "WH-EAST-01-C", "name": "Zone C - Pick & Pack", "type": "pick_pack", "temperature": "ambient"},
            {"code": "WH-EAST-01-D", "name": "Zone D - Cold Storage", "type": "cold_storage", "temperature": "refrigerated"},
            {"code": "WH-EAST-01-E", "name": "Zone E - Shipping", "type": "shipping", "temperature": "ambient"},
        ],
        "status": "active",
        "manager": "Mike Thompson",
    },
    {
        "id": "WH-WEST-01",
        "name": "West Coast Fulfillment Center",
        "location": {
            "street": "2500 Pacific Commerce Dr",
            "city": "Ontario",
            "state": "CA",
            "postal_code": "91761",
            "country": "US",
        },
        "type": "fulfillment_center",
        "total_capacity_sqft": 200000,
        "used_capacity_sqft": 140000,
        "zones": [
            {"code": "WH-WEST-01-A", "name": "Zone A - Inbound", "type": "receiving", "temperature": "ambient"},
            {"code": "WH-WEST-01-B", "name": "Zone B - General Storage", "type": "bulk_storage", "temperature": "ambient"},
            {"code": "WH-WEST-01-C", "name": "Zone C - High Value", "type": "secure_storage", "temperature": "ambient"},
            {"code": "WH-WEST-01-D", "name": "Zone D - Outbound", "type": "shipping", "temperature": "ambient"},
        ],
        "status": "active",
        "manager": "Jessica Liu",
    },
    {
        "id": "WH-CENT-01",
        "name": "Central Regional Warehouse",
        "location": {
            "street": "800 Heartland Blvd",
            "city": "Kansas City",
            "state": "MO",
            "postal_code": "64101",
            "country": "US",
        },
        "type": "regional_warehouse",
        "total_capacity_sqft": 80000,
        "used_capacity_sqft": 45000,
        "zones": [
            {"code": "WH-CENT-01-A", "name": "Zone A - Receiving/Shipping", "type": "receiving", "temperature": "ambient"},
            {"code": "WH-CENT-01-B", "name": "Zone B - Storage", "type": "bulk_storage", "temperature": "ambient"},
        ],
        "status": "active",
        "manager": "David Martinez",
    },
]

INVENTORY = [
    {
        "sku": "WIDGET-A100",
        "product_name": "Industrial Widget Type A",
        "warehouse_id": "WH-EAST-01",
        "zone": "WH-EAST-01-B",
        "location_bin": "B-12-03",
        "quantity_on_hand": 4500,
        "quantity_reserved": 500,
        "quantity_available": 4000,
        "reorder_point": 1000,
        "reorder_quantity": 5000,
        "unit": "EA",
        "last_counted": "2024-11-01",
        "unit_cost": 8.50,
    },
    {
        "sku": "WIDGET-A100",
        "product_name": "Industrial Widget Type A",
        "warehouse_id": "WH-WEST-01",
        "zone": "WH-WEST-01-B",
        "location_bin": "B-05-08",
        "quantity_on_hand": 3200,
        "quantity_reserved": 0,
        "quantity_available": 3200,
        "reorder_point": 1000,
        "reorder_quantity": 5000,
        "unit": "EA",
        "last_counted": "2024-11-05",
        "unit_cost": 8.50,
    },
    {
        "sku": "BOLT-SS-M10",
        "product_name": "Stainless Steel Bolt M10x50",
        "warehouse_id": "WH-EAST-01",
        "zone": "WH-EAST-01-B",
        "location_bin": "B-22-01",
        "quantity_on_hand": 25000,
        "quantity_reserved": 2000,
        "quantity_available": 23000,
        "reorder_point": 5000,
        "reorder_quantity": 20000,
        "unit": "EA",
        "last_counted": "2024-10-28",
        "unit_cost": 0.45,
    },
    {
        "sku": "SENSOR-TEMP-200",
        "product_name": "Temperature Sensor 200C Range",
        "warehouse_id": "WH-WEST-01",
        "zone": "WH-WEST-01-C",
        "location_bin": "C-02-01",
        "quantity_on_hand": 350,
        "quantity_reserved": 100,
        "quantity_available": 250,
        "reorder_point": 100,
        "reorder_quantity": 500,
        "unit": "EA",
        "last_counted": "2024-11-10",
        "unit_cost": 28.00,
    },
    {
        "sku": "CABLE-CAT6-100M",
        "product_name": "CAT6 Ethernet Cable 100m",
        "warehouse_id": "WH-EAST-01",
        "zone": "WH-EAST-01-B",
        "location_bin": "B-30-05",
        "quantity_on_hand": 120,
        "quantity_reserved": 50,
        "quantity_available": 70,
        "reorder_point": 100,
        "reorder_quantity": 200,
        "unit": "EA",
        "last_counted": "2024-11-08",
        "unit_cost": 55.00,
    },
    {
        "sku": "MOTOR-AC-5HP",
        "product_name": "AC Motor 5HP 3-Phase",
        "warehouse_id": "WH-CENT-01",
        "zone": "WH-CENT-01-B",
        "location_bin": "B-01-01",
        "quantity_on_hand": 18,
        "quantity_reserved": 0,
        "quantity_available": 18,
        "reorder_point": 5,
        "reorder_quantity": 20,
        "unit": "EA",
        "last_counted": "2024-11-12",
        "unit_cost": 520.00,
    },
    {
        "sku": "ENCL-IP65-LG",
        "product_name": "IP65 Enclosure Large",
        "warehouse_id": "WH-WEST-01",
        "zone": "WH-WEST-01-B",
        "location_bin": "B-15-02",
        "quantity_on_hand": 45,
        "quantity_reserved": 25,
        "quantity_available": 20,
        "reorder_point": 20,
        "reorder_quantity": 50,
        "unit": "EA",
        "last_counted": "2024-11-06",
        "unit_cost": 75.00,
    },
    {
        "sku": "VALVE-GATE-2IN",
        "product_name": "Gate Valve 2 inch Brass",
        "warehouse_id": "WH-EAST-01",
        "zone": "WH-EAST-01-B",
        "location_bin": "B-18-07",
        "quantity_on_hand": 80,
        "quantity_reserved": 0,
        "quantity_available": 80,
        "reorder_point": 50,
        "reorder_quantity": 200,
        "unit": "EA",
        "last_counted": "2024-11-02",
        "unit_cost": 18.00,
    },
    {
        "sku": "PIPE-PVC-4IN",
        "product_name": "PVC Pipe 4 inch x 10ft",
        "warehouse_id": "WH-CENT-01",
        "zone": "WH-CENT-01-B",
        "location_bin": "B-04-10",
        "quantity_on_hand": 300,
        "quantity_reserved": 0,
        "quantity_available": 300,
        "reorder_point": 100,
        "reorder_quantity": 500,
        "unit": "EA",
        "last_counted": "2024-10-30",
        "unit_cost": 12.00,
    },
]

STOCK_MOVEMENTS = [
    {
        "id": "SM-2024-00301",
        "type": "receipt",
        "sku": "WIDGET-A100",
        "product_name": "Industrial Widget Type A",
        "from_warehouse": None,
        "to_warehouse": "WH-EAST-01",
        "quantity": 5000,
        "reference": "PO-2024-00210",
        "status": "completed",
        "created_by": "system",
        "created_at": "2024-11-01T08:00:00Z",
        "completed_at": "2024-11-01T10:30:00Z",
    },
    {
        "id": "SM-2024-00302",
        "type": "shipment",
        "sku": "MOTOR-AC-5HP",
        "product_name": "AC Motor 5HP 3-Phase",
        "from_warehouse": "WH-CENT-01",
        "to_warehouse": None,
        "quantity": 10,
        "reference": "SO-2024-00125",
        "status": "completed",
        "created_by": "system",
        "created_at": "2024-11-18T14:00:00Z",
        "completed_at": "2024-11-18T16:00:00Z",
    },
    {
        "id": "SM-2024-00303",
        "type": "transfer",
        "sku": "WIDGET-A100",
        "product_name": "Industrial Widget Type A",
        "from_warehouse": "WH-EAST-01",
        "to_warehouse": "WH-WEST-01",
        "quantity": 2000,
        "reference": "TR-2024-00050",
        "status": "in_transit",
        "created_by": "jessica.liu",
        "created_at": "2024-11-19T09:00:00Z",
        "completed_at": None,
    },
    {
        "id": "SM-2024-00304",
        "type": "adjustment",
        "sku": "BOLT-SS-M10",
        "product_name": "Stainless Steel Bolt M10x50",
        "from_warehouse": "WH-EAST-01",
        "to_warehouse": None,
        "quantity": -150,
        "reference": "ADJ-2024-00012 (cycle count variance)",
        "status": "completed",
        "created_by": "mike.thompson",
        "created_at": "2024-10-28T15:00:00Z",
        "completed_at": "2024-10-28T15:30:00Z",
    },
]

PICKING_TASKS = [
    {
        "id": "PICK-2024-00401",
        "order_id": "SO-2024-00123",
        "warehouse_id": "WH-EAST-01",
        "status": "in_progress",
        "assigned_to": "warehouse_op_01",
        "items": [
            {"sku": "WIDGET-A100", "location_bin": "B-12-03", "quantity_requested": 500, "quantity_picked": 300},
            {"sku": "BOLT-SS-M10", "location_bin": "B-22-01", "quantity_requested": 2000, "quantity_picked": 2000},
        ],
        "priority": "high",
        "created_at": "2024-11-16T08:00:00Z",
        "started_at": "2024-11-16T08:30:00Z",
        "completed_at": None,
    },
    {
        "id": "PICK-2024-00402",
        "order_id": "SO-2024-00124",
        "warehouse_id": "WH-WEST-01",
        "status": "pending",
        "assigned_to": None,
        "items": [
            {"sku": "SENSOR-TEMP-200", "location_bin": "C-02-01", "quantity_requested": 100, "quantity_picked": 0},
            {"sku": "ENCL-IP65-LG", "location_bin": "B-15-02", "quantity_requested": 25, "quantity_picked": 0},
        ],
        "priority": "medium",
        "created_at": "2024-11-17T10:00:00Z",
        "started_at": None,
        "completed_at": None,
    },
]
